[project]
name = "resumechecker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "logfire>=0.16.1",  # Verify this version
    "pydantic-ai>=0.2.12",
    "python-dotenv>=1.0.1",
    "uvicorn[standard]>=0.30.6",
]